DROP INDEX BID;
DROP INDEX ATTR;
DROP INDEX CIN;
DROP INDEX DAYS;
DROP INDEX RID;
DROP INDEX SUBCG;
DROP INDEX USERID;

DROP TABLE Checkin;
DROP TABLE Review;
DROP TABLE Users;
DROP TABLE Attrs;
DROP TABLE SubCategory;
DROP TABLE MainCategory;
DROP TABLE Business;
DROP TABLE HOURS;
